Intex2022/Components/CountyViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Intex2022.Models;

namespace Intex2022.Components
{
    public class CountyViewComponent : ViewComponent
    {
        private ICrashRepository _context { get; set; }

        public CountyViewComponent(ICrashRepository temp)
        {
            _context = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCounty = RouteData?.Values["countySelect"];

            var county = _context.Crashes.Select(x => x.County_Name).Distinct().OrderBy(x => x);


            return View(county);
        }
    }
}

Intex2022/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using Intex2022.Models;
using Intex2022.Models.ViewModels;

namespace Intex2022.Controllers
{
    public class HomeController : Controller
    {
        private CrashDbContext _context { get; set; }
        private InferenceSession _session;
        private SignInManager<IdentityUser> signInManager;

        public HomeController(CrashDbContext context, InferenceSession session, SignInManager<IdentityUser> sim)
        {
            _context = context;
            _session = session;
            signInManager = sim;
        }


        //------------------ Landing Page ------------------//
        public IActionResult Index()
        {
            return View();
        }



        //------------------ PUBLIC READ LIST ------------------//
        public IActionResult AllList(string countySelect, int pageNum = 1)
        //public IActionResult CrashDetailsList(DateTime crashDate, int pageNum = 1)

        {
            var x = new CrashesViewModel
            {
                Crashes = _context.Crashes
                .OrderBy(p => p.County_Name),
                //.Skip((pageNum - 1) * pageSize)
                //.Take(pageSize),

            };

            return View(x);
        }




        //~~~~~~~~~~~~~~~ ADMIN FUNCTIONS ~~~~~~~~~~~~~~~//

        //------------------ Read List ------------------//

        [Authorize]
        public IActionResult CrashDetailsList(string countySelect)

        {
            //figure out filtering?
            var x = new CrashesViewModel
            {
                Crashes = _context.Crashes
                .Where(p => p.County_Name == countySelect || countySelect == null)
                .OrderBy(p => p.County_Name),
                //.Skip((pageNum - 1) * pageSize)
                //.Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumCrashes =
                    (countySelect == null ? _context.Crashes.Count()
                    : _context.Crashes.Where(p => p.County_Name == countySelect).Count()),
                    //TotalNumCrashes = _context.Crashes.Count(),
                    //CrashesPerPage = pageSize,
                    //CurrentPage = pageNum //idk
                }
            };

            return View(x);
        }


        //------------------ Add ------------------//
        [Authorize(Roles = "Administrator, test55")]
        [HttpGet]
        public IActionResult CreateCrashForm()
        {
            if (!(User.IsInRole("Administrator") || User.IsInRole("test55")))
            {

                return View("Error");
            }
            else
            {
                
                ViewBag.Crashes = _context.Crashes
                   .Select(c => c.City)
                   .Distinct()
                   .OrderBy(c => c)
                   .ToList();

                return View();
            }
        }

        [Authorize(Roles = "Administrator, test55")]
        [HttpPost]
        public IActionResult CreateCrash([FromForm] Crash crash)
        {
            if (!(User.IsInRole("Administrator") || User.IsInRole("test55")))
            {
                return View("Error");
            }
            else
            {


                int newCrashID = _context.Crashes.OrderBy(x => x.CRASH_ID).Last().CRASH_ID;
                crash.CRASH_ID = newCrashID + 1;
                crash.Crash_Date = crash.Crash_Date.Date;
                _context.Add(crash);
                _context.SaveChanges();
                return RedirectToAction("CrashDetailsList");
            }
        }

        //------------------ Edit/Update ------------------//
        [Authorize(Roles = "Administrator, test55")]
        [HttpGet]
        [Route("/Home/UpdateCrashForm/{id}")]
        public IActionResult UpdateCrashForm(int id)
        {
            ViewBag.Crashes = _context.Crashes
                .Select(c => c.City)
                .Distinct()
                .OrderBy(c => c)
                .ToList();
            Crash c = _context.Crashes.FirstOrDefault(c => c.CRASH_ID == id);
            return View(c);
        }

        [Authorize(Roles = "Administrator, test55")]
        [HttpPost]
        public IActionResult UpdateCrash([FromForm] Crash crash)
        {
            crash.Crash_Date = crash.Crash_Date.Date;
            _context.Update(crash);
            _context.SaveChanges();
            return RedirectToAction("CrashDetailsList");
        }

        IQueryable<Crash> Crashes => _context.Crashes;


        //---------------- Delete Confirmation / Deletion -----------------//
        [Authorize]
        [Route("/Home/DeleteConfirmation/{id}")]
        public IActionResult DeleteConfirmation(int id)
        {
            Crash crash = _context.Crashes.FirstOrDefault(c => c.CRASH_ID == id);
            return View("DeleteConfirmation", crash);
        }
        [Authorize(Roles= "Administrator, test55")]
        [Route("/Home/DeleteCrash/{id}")]
        public IActionResult DeleteCrash(int id)
        {
            Crash c = _context.Crashes.FirstOrDefault(c => c.CRASH_ID == id);
            _context.Crashes.Remove(c);
            _context.SaveChanges();
            return RedirectToAction("CrashDetailsList");
        }

        [HttpGet]
        public IActionResult Calculator()
        {
            return View();
        }

        //------------- Privacy Policy -----------//
        public IActionResult PrivacyPolicy()
        {
            return View();
        }

        //---------------- Predictor -----------------//
        [HttpPost]
        public IActionResult Calculator(crashData data)
        {
            var result = _session.Run(new List<NamedOnnxValue>
            {
                NamedOnnxValue.CreateFromTensor("float_input", data.AsTensor())
            });
            Tensor<float> score = result.First().AsTensor<float>();
            var prediction = new Prediction { PredictedValue = score.First() };
            result.Dispose();
            // Rounding to nearest integer for predictor and setting a limit on how high the predictor can calculate
            if (prediction.PredictedValue >= 4.5)
            {
                prediction.PredictedValue = 5;
            }
            else if (prediction.PredictedValue >= 3.5)
            {
                prediction.PredictedValue = 4;
            }
            else if (prediction.PredictedValue >= 2.5)
            {
                prediction.PredictedValue = 3;
            }
            else if (prediction.PredictedValue >= 1.5)
            {
                prediction.PredictedValue = 2;
            }
            else if (prediction.PredictedValue >= .5)
            {
                prediction.PredictedValue = 1;
            }
            return RedirectToAction("Calculation", prediction);
        }

        //---------------- Display Predictor Results -----------------//
        public IActionResult Calculation(Prediction prediction)
        {
            return View(prediction);
        }



    }
}

Intex2022/Views/Home/AllList.cshtml
@*All List Page
    - This is the publics page for the data base list
    - From this page the public can view all of the crashes
    - The public does not have the ability to Add, Edit, or Delete any crash records from the database
*@


@{
    ViewData["Title"] = "List of All";
}

@model CrashesViewModel

<div class="row m-1 p-1">
    @*<div id="county" class="col-2">
        <vc:county></vc:county>
    </div>*@


    <div class="col-12">
        <div class="text-center">
            <h1 class="display-4">Utah Vehicle Crash Information</h1>
        </div> 

        <div class="container-fluid px-4">
            <br />

            <div class="card mb-4">
                <div class="card-header">
                    *Crash Severity (1 = no injury, 2 = possible injury, 3 = suspected minor injury, 4 = suspected serious injury, 5 = fatal)

                </div>
                <div class="card-body">
                    <table id="datatablesSimple">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Date/Time</th>
                                <th>Route</th>
                                <th>Milepoint</th>
                                <th>Latitude, Longitude</th>
                                <th>Main Road</th>
                                <th>City</th>
                                <th>County</th>
                                <th>*Crash Severity</th>
                                <th>Tags</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Crash c in Model.Crashes)
                            {
                                <tr>
                                    <td>@c.CRASH_ID</td>
                                    <td>@c.Crash_Date.ToShortDateString(), @c.Crash_Time</td>
                                    <td>@c.Route</td>
                                    <td>@c.Milepoint</td>
                                    <td>(@c.Lat_Utm_Y, @c.Long_Utm_X)</td>
                                    <td>@c.Main_Road_Name</td>
                                    <td>@c.City</td>
                                    <td>@c.County_Name</td>
                                    <td>@c.Crash_Severity_ID</td>

                                    <td>
                                        @if (@c.Work_Zone_Related is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Work Zone Related</span>
                                        }
                                        @if (@c.Pedestrian_Involved is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Pedestrian Involved</span>
                                        }
                                        @if (@c.Bicyclist_Involved is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Bicyclist Involved</span>
                                        }
                                        @if (@c.Motorcycle_Involved is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Motorcycle Involved</span>
                                        }
                                        @if (@c.Improper_Restraint is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Improper Restraint</span>
                                        }
                                        @if (@c.Unrestrained is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Unrestrained</span>
                                        }
                                        @if (@c.DUI is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">DUI</span>
                                        }
                                        @if (@c.Intersection_Related is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Intersection Related</span>
                                        }
                                        @if (@c.Wild_Animal_Related is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Wild Animal Related</span>
                                        }
                                        @if (@c.Domestic_Animal_Related is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Domestic Animal Related</span>
                                        }
                                        @if (@c.Overturn_Rollover is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Overturn Rollover</span>
                                        }
                                        @if (@c.Commercial_Motor_VEH_Involved is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Commercial Motor Vehicle Involved</span>
                                        }
                                        @if (@c.Teenage_Driver_Involved is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Teenage Driver Involved</span>
                                        }
                                        @if (@c.Older_Driver_Involved is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Older Driver Involved</span>
                                        }
                                        @if (@c.Night_Dark_Condition is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Night/Dark Conditions</span>
                                        }
                                        @if (@c.Single_Vehicle is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Single Vehicle</span>
                                        }
                                        @if (@c.Distracted_Driver is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Distracted Driving</span>
                                        }
                                        @if (@c.Drowsy_Driver is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Drowsy Driving</span>
                                        }
                                        @if (@c.Roadway_Departure is true)
                                        {
                                            <span class="badge rounded-pill bg-primary text-light">Roadway Departure</span>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Intex2022/Views/Home/Calculation.cshtml
@model Prediction

<div style="text-align: center; list-style-position: inside; ">
    
    <h1 >Severity:@Model.PredictedValue</h1>
    <h5 >Severity Scale</h5>

    <ol>
        <li>No injury (Yeeeeet)</li>
        <li>Possible injury</li>
        <li>Suspected minor injury</li>
        <li>Suspected serious injury</li>
        <li>Fatal</li>
    </ol>
    <p>
        This predictor is able to predict the severity of a crash based on many different details and scenarios. It is can be used to see what kind of danger someone is in when driving under those conditions. By educating and teaching we will be able to create safer situations for everyone around us. 
    </p>
</div>

Intex2022/Views/Home/CrashDetailsList.cshtml
@*Crash Details List Page
    - This is the Admin page for the data base list
    - From this page Admins have the following abilities
        - Add crashes
        - Delete crashes
        - Edit crashes
        - View crashes
    *@


@*<a href="/Account/Logout" class="btn btn-success">Logout</a>*@
    </div>
</div>
﻿@{
    ViewData["Title"] = "List of All";
}

@model CrashesViewModel

<div class="row m-1 p-1">
    <div id="county" class="col-1">
        <vc:county></vc:county>
    </div>

    <main class="col-11">
        <div class="container-fluid px-4">
            <h1 class="mt-4">Utah Crash Data</h1>

            <div class="card mb-4">
                <div class="card-body">
                    The data set is from The Crash Studies Team at UDOT's Traffic & Safety Division who maintains a
                    detailed database of all crashes on public roadways in Utah. This data is used to report
                    safety trends, identify potential safety improvement projects, and allocate limited funding
                    to projects that will have the greatest impact on safety. This data and all UDOT Safety
                    Program information are protected under 23 USC 409 and therefore inadmissible in court.
                </div>
            </div>
            
            <div class="card mb-4">
                <div class="card-header text-white bg-dark">
                    *Crash Severity (1 = no injury, 2 = possible injury, 3 = suspected minor injury, 4 = suspected serious injury, 5 = fatal)

                </div>
                <div class="card-body">
                    <table id="datatablesSimple" class="caption-top">
                        <caption>
                            @if (User.IsInRole("Administrator") || User.IsInRole("test55"))
                            {
                                <a href="/Home/CreateCrashForm" class="btn btn-primary">+ Add Crash</a>
                            }
                        </caption>
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Date/Time</th>
                                <th>Route</th>
                                <th>Milepoint</th>
                                <th>Latitude, Longitude</th>
                                <th>Main Road</th>
                                <th>City</th>
                                <th>County</th>
                                <th>*Crash Severity</th>
                                <th>Crash Conditions</th>
                                @if (User.IsInRole("Administrator") || User.IsInRole("test55"))
                                {
                                <th>Actions</th>
                                }

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Crash c in Model.Crashes)
                            {
                            <tr>
                                <td>@c.CRASH_ID</td>
                                <td>@c.Crash_Date.ToShortDateString(), @c.Crash_Time</td>
                                <td>@c.Route</td>
                                <td>@c.Milepoint</td>
                                <td>(@c.Lat_Utm_Y, @c.Long_Utm_X)</td>
                                <td>@c.Main_Road_Name</td>
                                <td>@c.City</td>
                                <td>@c.County_Name</td>
                                <td>@c.Crash_Severity_ID</td>

                                <td>
                                    @if (@c.Work_Zone_Related is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Work Zone Related</span>
                                    }
                                    @if (@c.Pedestrian_Involved is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Pedestrian Involved</span>
                                    }
                                    @if (@c.Bicyclist_Involved is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Bicyclist Involved</span>
                                    }
                                    @if (@c.Motorcycle_Involved is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Motorcycle Involved</span>
                                    }
                                    @if (@c.Improper_Restraint is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Improper Restraint</span>
                                    }
                                    @if (@c.Unrestrained is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Unrestrained</span>
                                    }
                                    @if (@c.DUI is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">DUI</span>
                                    }
                                    @if (@c.Intersection_Related is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Intersection Related</span>
                                    }
                                    @if (@c.Wild_Animal_Related is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Wild Animal Related</span>
                                    }
                                    @if (@c.Domestic_Animal_Related is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Domestic Animal Related</span>
                                    }
                                    @if (@c.Overturn_Rollover is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Overturn Rollover</span>
                                    }
                                    @if (@c.Commercial_Motor_VEH_Involved is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Commercial Vehicle Involved</span>
                                    }
                                    @if (@c.Teenage_Driver_Involved is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Teenage Driver Involved</span>
                                    }
                                    @if (@c.Older_Driver_Involved is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Older Driver Involved</span>
                                    }
                                    @if (@c.Night_Dark_Condition is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Night/Dark Conditions</span>
                                    }
                                    @if (@c.Single_Vehicle is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Single Vehicle</span>
                                    }
                                    @if (@c.Distracted_Driver is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Distracted Driving</span>
                                    }
                                    @if (@c.Drowsy_Driver is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Drowsy Driving</span>
                                    }
                                    @if (@c.Roadway_Departure is true)
                                    {
                                        <span class="badge rounded-pill bg-primary">Roadway Departure</span>
                                    }


                                </td>
                                @if (User.IsInRole("Administrator") || User.IsInRole("test55"))
                                {
                                    <td>
                                        <div class="btn-group">
                                            <a class="btn btn-warning btn-sm" href="/Home/UpdateCrashForm/@c.CRASH_ID"><i class="bi bi-pencil-square" style="color:white"></i></a>
                                            <a class="btn btn-danger btn-sm" href="/Home/DeleteConfirmation/@c.CRASH_ID"><i class="bi bi-trash3"></i></a>
                                        </div>
                                    </td>
                                }
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>

Intex2022/Views/Home/DeleteConfirmation.cshtml
@*Delete Confirmation Page
    - This page is a deletion confirmation page before a admin deletes a record
    - It contains a confirm Delete button before the crash record is removed from the database*@


@{
    ViewData["Title"] = "Delete Crash";
}

@model Crash

<h2>Confirm Deletion</h2>
<h3>Are you sure you want to delete the crash with Crash ID: @Model.CRASH_ID ?</h3>
<a class="btn btn-danger btn-sm" href="/Home/DeleteCrash/@Model.CRASH_ID">Delete</a>
<div>
    <a asp-area="" asp-controller="Home" asp-action="CrashDetailsList" class="btn btn-primary"><i class="bi bi-chevron-left"></i> Return to Crash Data </a>
</div>
<input type="hidden" asp-for="CRASH_ID" />

Intex2022/Views/Home/Index.cshtml
@*Main Page
    - This is the main landing page
    - Contains details of the website
    - Contains routing to all of the rest of the website
*@
@{
    ViewData["Title"] = "Home Page";
}

@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<partial name="_CookieConsentPartial" />

<div class="text-center">
    <h1 class="display-4">Protect Utah Roads: Crash Information and Prevention</h1>

    <p>
        This is an important resource to help make informed decisions about how we can reduce motor vehicle accidents.
        Utah roads have seen an increase in motor vehicle crashes in recent years. This site
        explores the different factors playing into all the crashes and displays the data for each one. Read on
        to <a href="/Home/Calculator">Learn More</a>.
    </p>

    <br />
    <iframe width="560" height="315" src="https://www.youtube.com/embed/ELg0waAnYjA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <br />
    <br /><br />
    <hr />
    <br /><br />
    <h3>Utah Crash Summary Statistics</h3>
    <iframe width="500" height="350" src="https://udps.numetric.net/utah-crash-summary#/70b04672-a17d-4572-9706-510ceb81c56a" frameborder="0"></iframe>
    <iframe width="500" height="350" src="https://udps.numetric.net/utah-crash-summary#/34d06948-6adb-499e-b14b-60067338b2c0" frameborder="0"></iframe>
    <iframe width="500" height="350" src="https://udps.numetric.net/utah-crash-summary#/c6738091-50dc-4702-bb6e-6f093cae7952" frameborder="0"></iframe>
    <iframe width="500" height="350" src="https://udps.numetric.net/utah-crash-summary#/b35a2013-c4fd-40f6-bd89-76fff2bed2a4" frameborder="0"></iframe>
    <br />

</div>